import { toTemplateHtml, applyTemplate } from '@/services/templates';

const CTX = {
  studentFirstName: 'John',
  studentLastName: 'Doe',
  studentFullName: 'John Doe',
  universityName: 'University of Florida',
};

describe('toTemplateHtml', () => {
  test('replaces student names with PascalCase tags', () => {
    const html = '<p>Hello, my name is John Doe.</p><p>First: John, Last: Doe</p>';
    const result = toTemplateHtml(html, CTX);
    expect(result).toContain('{{StudentFullName}}');
    expect(result).toContain('{{StudentFirstName}}');
    expect(result).toContain('{{StudentLastName}}');
    expect(result).not.toContain('John Doe');
    expect(result).not.toContain('>John<');
  });

  test('replaces university name with PascalCase tag', () => {
    const html = '<p>I am interested in University of Florida.</p>';
    const result = toTemplateHtml(html, CTX);
    expect(result).toContain('{{UniversityName}}');
    expect(result).not.toContain('University of Florida');
  });

  test('does NOT produce {{CoachList}} tag', () => {
    const html = '<p>Ada Lovelace, Alan Turing</p>';
    const result = toTemplateHtml(html, CTX);
    expect(result).not.toContain('{{CoachList}}');
  });

  test('does NOT produce {{PrimaryCoachLastName}} tag', () => {
    const html = '<p>Hello Coach Smith,</p>';
    const result = toTemplateHtml(html, CTX);
    expect(result).not.toContain('{{PrimaryCoachLastName}}');
  });

  test('preserves snake_case intro tags unchanged', () => {
    const html = '<p>Hello Coach {{coach_last_name}},</p><p>at {{university_name}}</p>';
    const result = toTemplateHtml(html, CTX);
    expect(result).toContain('{{coach_last_name}}');
    expect(result).toContain('{{university_name}}');
  });
});

describe('applyTemplate', () => {
  test('resolves PascalCase student tags back to values', () => {
    const html = '<p>{{StudentFullName}} ({{StudentFirstName}} {{StudentLastName}})</p>';
    const result = applyTemplate(html, CTX);
    expect(result).toBe('<p>John Doe (John Doe)</p>');
  });

  test('resolves {{UniversityName}} back to value', () => {
    const html = '<p>Interested in {{UniversityName}}</p>';
    const result = applyTemplate(html, CTX);
    expect(result).toBe('<p>Interested in University of Florida</p>');
  });

  test('does NOT resolve {{CoachList}}', () => {
    const html = '<p>Coaches: {{CoachList}}</p>';
    const result = applyTemplate(html, CTX);
    expect(result).toContain('{{CoachList}}');
  });

  test('does NOT resolve {{PrimaryCoachLastName}}', () => {
    const html = '<p>Coach {{PrimaryCoachLastName}}</p>';
    const result = applyTemplate(html, CTX);
    expect(result).toContain('{{PrimaryCoachLastName}}');
  });

  test('passes snake_case intro tags through unresolved', () => {
    const html = '<p>Hello Coach {{coach_last_name}},</p><p>at {{university_name}}</p>';
    const result = applyTemplate(html, CTX);
    expect(result).toContain('{{coach_last_name}}');
    expect(result).toContain('{{university_name}}');
  });
});

describe('round-trip: toTemplateHtml → applyTemplate', () => {
  test('student names survive save→load round-trip', () => {
    const original = '<p>Hello, I am John Doe from Springfield.</p>';
    const saved = toTemplateHtml(original, CTX);
    expect(saved).toContain('{{StudentFullName}}');

    const loaded = applyTemplate(saved, CTX);
    expect(loaded).toBe(original);
  });

  test('university name survives save→load round-trip', () => {
    const original = '<p>I want to attend University of Florida.</p>';
    const saved = toTemplateHtml(original, CTX);
    expect(saved).toContain('{{UniversityName}}');

    const loaded = applyTemplate(saved, CTX);
    expect(loaded).toBe(original);
  });

  test('snake_case intro tags survive the full lifecycle', () => {
    const autoGenerated =
      '<p>Hello Coach {{coach_last_name}},</p>' +
      '<p>John Doe - {{university_name}}</p>';

    const saved = toTemplateHtml(autoGenerated, CTX);
    expect(saved).toContain('{{coach_last_name}}');
    expect(saved).toContain('{{university_name}}');
    expect(saved).toContain('{{StudentFullName}}');

    const loaded = applyTemplate(saved, CTX);
    expect(loaded).toContain('{{coach_last_name}}');
    expect(loaded).toContain('{{university_name}}');
    expect(loaded).toContain('John Doe');
  });
});
